markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: 刘洋的博客
description: 刘洋的博客
keywords: 前端
url: http://imbolo.github.io
feed: /atom.xml
favicon: http://tp2.sinaimg.cn/2398850605/180/5637464885/1

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html
  - text: 求收留
    url: /resume/index.html

#Author config
author:
    name: 刘洋
    email: imbolo@qq.com
    imageLink: http://tp2.sinaimg.cn/2398850605/180/5637464885/1
    simpleIntro: <h4>一只正在成为前端攻城师的刘洋</h4> 
    detailIntro: 热衷前端开发，对JS模块化开发很有兴趣。对hybrid app和air等跨平台移动开发非常熟悉，有上线单页面应用经验。<br/>熟悉Android开发，有在Google Play、安卓市场等上线的独立小游戏作品。<br/>会做UI切图，能和美工轻松合作。<br/>Shell爱好者，Mac OSX/Linux重度用户。

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/imbolo
  - class: icon-github-alt
    url: https://github.com/imbolo
  - class: icon-twitter
    url: http://twitter.com/mrbolo


#Links
customLinks:
  - item:
    - text: 印象童年
      url: http://www.kidshow.com.cn
    - text: 掌心
      url: http://www.zhanxin.info
    - text: Mr.Coder
      url: http://www.mrcoder.org
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-44427951-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: imbolo
